stages:
  train:
    cmd: python main.py
    deps:
      - main.py
      - src/
      - data/raw/Concrete_Data.csv
      - params.yaml
    params:
      - split
      - model
      - training
    outs:
      - models/best_model.pkl
      - models/scaler.pkl
    metrics:
      - reports/metrics.json